# Player names used as keys in output JSON
BRANDON = "brandon"
BREE = "bree"
BRIAN = "brian"
CADE = "cade"
DARWIN = "darwin"
ELKE = "elke"
JOSH = "josh"
LINDSEY = "lindsey"
SOPHIE = "sophie"
STEVE = "steve"
STEVEN = "steven"
SUN = "sun"
SUSI = "susi"
SUSU = "susu"
TANG = "tang"
YANG = "yang"
